import type { RegexExample } from '../types/regex'

export const regexExamples: RegexExample[] = [
  {
    id: 'email',
    name: 'Email',
    description: 'Common email address validation',
    pattern: '[\\w.+-]+@[\\w-]+\\.[\\w.]+',
    flags: ['g'],
    sampleText: 'Contact us at support@example.com or sales.team@company-site.org for more info.',
  },
  {
    id: 'url',
    name: 'URL',
    description: 'HTTP and HTTPS URLs with optional path',
    pattern: 'https?:\\/\\/[\\w.-]+(?::\\d+)?(?:\\/[^\\s]*)?',
    flags: ['g'],
    sampleText: 'Visit https://example.com/path?q=1 or http://localhost:3000/docs for details.',
  },
  {
    id: 'iso-date',
    name: 'ISO Date',
    description: 'Dates in YYYY-MM-DD format with capture groups',
    pattern: '(?<year>\\d{4})-(?<month>\\d{2})-(?<day>\\d{2})',
    flags: ['g'],
    sampleText: 'Deadlines: 2025-01-15 for phase one, 2025-06-30 for the final release.',
  },
  {
    id: 'ipv4',
    name: 'IPv4 Address',
    description: 'Valid IPv4 octets (0-255)',
    pattern: '\\b(?:(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\.){3}(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\b',
    flags: ['g'],
    sampleText: 'Servers: 192.168.1.1, 10.0.0.255, and an invalid 999.1.2.3 address.',
  },
  {
    id: 'hex-color',
    name: 'Hex Color',
    description: 'CSS hex colors (#RGB, #RRGGBB, #RRGGBBAA)',
    pattern: '#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}(?:[0-9a-fA-F]{2})?)\\b',
    flags: ['g', 'i'],
    sampleText: 'Palette: #fff background, #1e40af primary, #F97316 accent, #22c55e80 overlay.',
  },
  {
    id: 'slug',
    name: 'Slug',
    description: 'URL-friendly slug segments',
    pattern: '[a-z0-9]+(?:-[a-z0-9]+)*',
    flags: ['g'],
    sampleText: 'Routes: /blog/hello-world, /docs/getting-started, /products/item-42.',
  },
  {
    id: 'phone',
    name: 'Intl. Phone',
    description: 'International phone numbers with optional country code',
    pattern: '\\+?\\d{1,3}[-.\\s]?\\(?\\d{1,4}\\)?[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,9}',
    flags: ['g'],
    sampleText: 'Call +1 (555) 123-4567, +34 912 345 678, or 555.123.4567 today.',
  },
  {
    id: 'username',
    name: 'Username',
    description: '3-16 chars, letters, numbers, underscore (anchored)',
    pattern: '^[a-zA-Z0-9_]{3,16}$',
    flags: ['m'],
    sampleText: 'john_doe\nuser with spaces\nab\nvalid_user_99',
  },
  {
    id: 'password',
    name: 'Strong Password',
    description: 'Lookaheads: 8+ chars with upper, lower, digit and symbol',
    pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^\\w\\s]).{8,}$',
    flags: ['m'],
    sampleText: 'WeakPass1\nStr0ng!Pass\nshort!A1\nAnother$ecure99',
  },
  {
    id: 'html-tag',
    name: 'HTML Tag',
    description: 'Opening/closing tags with tag name capture',
    pattern: '<(\\/?)([a-zA-Z][a-zA-Z0-9]*)\\b[^>]*>',
    flags: ['g'],
    sampleText: '<div class="box"><p>Hello</p><br/><span>World</span></div>',
  },
]
